name: Deploy site to GitHub Pages

# Adapted from https://gohugo.io/host-and-deploy/host-on-github-pages/

# Run when when a 'deploy/**' tag is pushed or when dispatched manually.
on:
  push:
    tags:
      - deploy/**
  workflow_dispatch:

# Grant permissions to deploy to GitHub pages.
permissions:
  contents: read
  pages: write
  id-token: write

# Limit to one deployment at a time and always finish pending jobs.
concurrency:
  group: pages
  cancel-in-progress: false

# Run commands using Bash.
defaults:
  run:
    shell: bash

# Generate, upload, and deploy site.
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DART_SASS_VERSION: 1.89.2
      HUGO_VERSION: 0.148.1
      HUGO_ENVIRONMENT: production
      TZ: Europe/London
    steps:
      - name: Install Hugo
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb
          sudo dpkg -i ${{ runner.temp }}/hugo.deb
      # # Uncomment if using Dart Sass:
      # - name: Install Dart Sass
      #   run: |
      #     wget -O ${{ runner.temp }}/dart-sass.tar.gz https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz
      #     tar -xf ${{ runner.temp }}/dart-sass.tar.gz --directory ${{ runner.temp }}
      #     mv ${{ runner.temp }}/dart-sass/ /usr/local/bin
      #     echo "/usr/local/bin/dart-sass" >> $GITHUB_PATH
      - name: Checkout repository
        uses: actions/checkout@v4
        # # Uncomment if using Git submodules:
        # with:
        #   submodules: recursive
        #   fetch-depth: 0
      - name: Configure GitHub Pages
        id: pages
        uses: actions/configure-pages@v5
      # # Uncomment if using Node.js packages:
      # - name: Install Node.js packages
      #   run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
      - name: Restore cache
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{ runner.temp }}/hugo_cache
          key: hugo-${{ github.run_id }}
          restore-keys:
            hugo-
      - name: Configure Git
        run: git config core.quotepath false
      - name: Generate site with Hugo
        run: |
          hugo \
            --gc \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/" \
            --cacheDir "${{ runner.temp }}/hugo_cache"
      - name: Save cache
        id: cache-save
        uses: actions/cache/save@v4
        with:
          path: |
            ${{ runner.temp }}/hugo_cache
          key:  ${{ steps.cache-restore.outputs.cache-primary-key }}
      - name: Upload generated site
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy uploaded site to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
